version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq_data:/data
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: on-failure
    ports:
      - 5672:5672
      - 15671:15671
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 5
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    networks:
      - app-network

  server:
    container_name: server
    build:
      context: '.'
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - CONN_URL=amqp://rabbitmq:5672
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "5005:5005"
    restart: always
    networks:
      - app-network
      - oceansmap
    command: node app.js

  workers:
    container_name: workers
    build:
      context: '.'
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
      - server
    environment:
      - CONN_URL=amqp://rabbitmq:5672
      - MONGO_URL=mongodb://mongo:27017
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 50M
    networks:
      - app-network
    command: node clusteredWorker.js

volumes:
  rabbitmq_data: {}

networks:
  app-network:
    driver: bridge
  oceansmap:
    external: true
